export const gamesList = [
  {
    id: 1,
    game_icon: "GiBasketballBall",
    date_icon: "FcCalendar",
    title: "Basketball Game",
    subTitle: "Basketball, Age:18+",
    date: "mon, Jun 27",
    hour: "6:30 p.m",
    duration: "80",
    price: "6.77",
    location: "Waterio Memorial Recreation Complex - Activity Court (Indoor)",
    numberOfPlayers: 8,
    whiteTeam: {
      1: { name: "Adem w 1" },
      2: { name: "Murat w 2" },
      4: { name: "test w 4" },
    },
    blackTeam: {
      1: { name: "Adem b 1" },
      2: { name: "Murat b 2" },
      4: { name: "test b 4" },
    },
  },
  {
    id: 2,
    game_icon: "GiHockey",
    date_icon: "FcCalendar",
    title: "Ice Hockey",
    subTitle: "Ice Hockey, Ages:18+",
    date: "Tue, Jun 28",
    hour: "1:00 p.m",
    duration: "90",
    price: "88.5",
    location: "Mohowk 4 ice - Icve Rink (Indoor)",
    numberOfPlayers: 11,
    whiteTeam: {
      4: { name: "Adem w 4" },
      6: { name: "Murat w 6" },
      9: { name: "test w 9" },
    },
    blackTeam: {
      4: { name: "Murat b 4" },
      6: { name: "test b 6" },
      9: { name: "test b 9" },
    },
  },
  {
    id: 3,
    game_icon: "GiAmericanFootballBall",
    date_icon: "FcCalendar",
    title: "Soccer Game",
    subTitle: "Soccer, Ages:18+",
    date: "Tue, Jun 28",
    hour: "9:00 p.m",
    duration: "50",
    price: "6.77",
    location: "RIM Park-Field House 2 (Indoor)",
    numberOfPlayers: 7,
    whiteTeam: {
      2: { name: "Adem w 10" },
      5: { name: "test w 11" },
      6: { name: "Murat w 12" },
    },
    blackTeam: {
      1: { name: "Adem b 10" },
      3: { name: "test b 11" },
      7: { name: "Murat b 12" },
    },
  },
  {
    id: 4,
    game_icon: "GiVolleyballBall",
    date_icon: "FcCalendar",
    title: "Volleyball Game",
    subTitle: "Volleyball, Ages:18+",
    date: "Wed, Jun 29",
    hour: "10:45 p.m",
    duration: "90",
    price: "6.77",
    location: "Waterloo Memorial Recreation Complex-Activity Court (Indoor)",
    numberOfPlayers: 8,
    whiteTeam: { 4: { name: "Adem w 4" } },
    blackTeam: {
      4: { name: "Adem b 4" },
    },
  },
  {
    id: 5,
    game_icon: "GiAmericanFootballBall",
    date_icon: "FcCalendar",
    title: "Soccer Game",
    subTitle: "Soccer' Ages:18+",
    date: "Tue' Jun 28",
    hour: "10:00 p.m",
    duration: "50",
    price: "6.77",
    location: "RIM Park - Field House 3 (Indoor)",
    numberOfPlayers: 7,
    whiteTeam: {
      5: { name: "Adem w 5" },
    },
    blackTeam: {
      3: { name: "Adem b 3" },
    },
  },
];
