export const gamesList = [
  {
    id: 1,
    game_icon: "GiBasketballBall",
    date_icon: "FcCalendar",
    title: "Basketball Game",
    subTitle: "Basketball, Age:18+",
    date: "mon, Jun 27",
    hour: "6:30 p.m",
    duration: "80",
    price: "6.77",
    location: "Waterio Memorial Recreation Complex - Activity Court (Indoor)",
  },
  {
    id: 2,
    game_icon: "GiHockey",
    date_icon: "FcCalendar",
    title: "Ice Hockey",
    subTitle: "Ages:18+",
    date: "Tue, Jun 28",
    hour: "1:00 p.m",
    duration: "90",
    price: "88.5",
    location: "Mohowk 4 ice - Icve Rink (Indoor)",
  },
  {
    id: 3,
    game_icon: "GiAmericanFootballBall",
    date_icon: "FcCalendar",
    title: "Soccer Game",
    subTitle: "Soccer, Ages:18+",
    date: "Tue, Jun 28",
    hour: "9:00 p.m",
    duration: "50",
    price: "6.77",
    location: "RIM Park-Field House 2 (Indoor)",
  },
  {
    id: 4,
    game_icon: "GiVolleyballBall",
    date_icon: "FcCalendar",
    title: "Volleyball Game",
    subTitle: "Volleyball, Ages:18+",
    date: "Wed, Jun 29",
    hour: "10:45 p.m",
    duration: "90",
    price: "6.77",
    location: "Waterloo Memorial Recreation Complex-Activity Court (Indoor)",
  },
  {
    id: 5,
    game_icon: "GiAmericanFootballBall",
    date_icon: "FcCalendar",
    title: "Soccer Game",
    subTitle: "Soccer' Ages:18+",
    date: "Tue' Jun 28",
    hour: "10:00 p.m",
    duration: "50",
    price: "6.77",
    location: "RIM Park - Field House 3 (Indoor)",
  },
];
